mode: cat-life

starting-score: 9

server-locale: en_US # default to en_US if not specified. as interactable menus (revival menu)
                     # cannot have items be translated server side, we need to specify which bundle to get them from
                     # here.

categories:
  green:
    colour: GREEN
    score: 6 # mininum number of minutes required to be in this category OR mininum number of lives.

  yellow:
    colour: YELLOW
    score: 3
    can-kill:
      - green

  red:
    colour: 'RED' # as displayed in tab & above head
    score: 1 # the lowest category should set 0 here to ignore this category entirely.
    can-kill: # does not prevent PvP, just determines which categories players can be rewarded time from.
      - red
      - yellow
      - green

# these items will delete from inventories if players have them. if a recipe exists, it will try to prevent crafting it
# bypass permission: life.bypass.banned-items
banned-items:
  - BOOKSHELF
  - ENCHANTED_GOLDEN_APPLE
  - ENCHANTING_TABLE

# this will prevent players from having certain enchantments
# bypass permission: life.bypass.banned-enchantments
banned-enchantments:
  max-level: 3 # set to -1 to disable. 0 will disable enchantments entirely.
  # blocklist of enchantments.
  blocklist:
    - bane_of_arthropods

revival:
  enabled: true
  announce:
    title:
      enabled: true
      totem: true # set to 'false' to use text title
      sound: ENTITY_ENDER_DRAGON_DEATH # set to 'NONE' to disable announcement sound
    beam:
      enabled: true
      time: 20
  item:
    name: "Revival Clock"
    block: CLOCK
    #model: "cosmetics:witch_hat" # comment out to omit
    recipe: [ DIRT, DIRT, DIRT,     # replace empty slots with EMPTY
              DIRT, DIRT, DIRT,
              DIRT, DIRT, DIRT ]
  added-score: 300

custom-recipes:
  minimal-saddle:
    block: SADDLE
    recipe: [ EMPTY,  EMPTY,    EMPTY,     # replace empty slots with EMPTY
              EMPTY,  LEATHER,  EMPTY,
              LEATHER,EMPTY,    LEATHER ]
  paper-tnt:
    block: TNT
    recipe: [ PAPER,  SAND,       PAPER,
              SAND,   GUNPOWDER,  SAND,
              PAPER,  SAND,       PAPER ]
  slimeballs:
    quantity: 3
    block: SLIME_BALL
    recipe: [ EMPTY,    BONE_MEAL,   EMPTY,
              BONE_MEAL,SUGAR_CANE,  BONE_MEAL,
              EMPTY,    WATER_BUCKET,EMPTY ]
  craftable-tags:
    block: NAME_TAG
    shapeless: true
    recipe: [STRING, PAPER]



options:
  spawn-eggs:
    droppable: true
    chance: 5 # 0-100

  boogeyman:
    auto-roll: true # roll at session start
    min: 1
    max: 3
    failure:
      do-not-punish-teams:
        - red
      punish-lowest-team: false
      demote-to-next-team: true
      demotion-score: 10000 # used if `demote-to-next-team` is false
    lowest-tier-is-penalised: false # lowest lives team is not penalized when true. (i.e if red is allowed, reds wont -2h)
    punish-boogeys: true # auto punish boogeys at end of session

    allowed-teams: # names must match categories in `categories` configuration.
      - green
      - yellow

  cat-life:
    auto-disguise: true

  secret-life:
    auto-roll: true # roll at session start
    group-tasks:
      only-same-team: true
      default-assignment-limit: 4 # if this is removed it will be overriden by a fall back value.
                                  # the way group tasks are selected may mean an absurd proportion of the playerbase
                                  # is assigned a single group task, so this is neccessary for happy gameplay
    group-task-only-same-team: true
    watchdog-time: 3600 # ~3 minutes
    gamemaster-enabled: true # set to false to place onus of task guess acceptance on owning player, tasks that use
                             # GM verification will be automatically accepted.
    can-guess-tasks:
      - red
      - yellow
    can-reroll:
      times: 1
      teams:
        - red
    task-deck:
      easy:                 # Currently there is no concept outside of `easy, medium, hard`. do not try to add additional categories.
        teams:              # Teams that are eligible to recieve these tasks
          - green
          - yellow
        deck:               # Tasks that are considered "easy"
          - follow-another-player # todo more tasks
          - meow-at-others
          - duck-hunt
      normal:
        teams:
          - yellow
          - red
        deck:
          - follow-another-player
      hard:
        teams:
          - red
        deck:
          - explode-another-player
          - chest-head
          - wither-warden-war
    failure:              # prevent a specific team from
      do-not-punish-teams:
        - red
    task-configs:
      defaults:
        generic-radius-threshold: 32
      test-group-task:
        min-assignment: 3
        assignment-limit: 5
      explode-another-player:
        assignment-limit: 1
      pass-it-on:
        save-old-task: true
      waffle-monster:
        item:
          recipe: [ WHEAT, WHEAT, EMPTY,
                    WHEAT, WHEAT, EMPTY,
                    EMPTY, EMPTY, EMPTY ]
          block: CAKE
          model: lifeseries:waffle
        sounds:
          spawn: lifeseries:waffle-spawn
          death: lifeseries:waffle-death
      chest-head:
        grace: 30
        head-url: "http://textures.minecraft.net/texture/275bcff2e74deed37a319a1f404e70d06a5f360cacee99c71346f38560cbd72a"
        ball-launcher:
          enabled: true
          prevent-sharing: true
          #model: "cosmetics:witch_hat" # omit if you just want breeze balls.
        loot:
          - name: revival-item # refer to as special
            quantity: 1
          - name: DIAMOND
            quantity: 9
          - name: TNT
            quantity: 16
      arbitrary-string-task:
        build-a-house:
          name: "Build a house"
          require-verification: true
          guessable: true
          allowed-teams:
            - red
            - yellow
            - green
          is-group: true # default: false
          group: # this section can be omitted if `is-group` is false.
            min: 2
            max: 5
            limit-to-team: true


  rewards:
    disable-on-disallowed-team: true
    kill: 1800
    boogey-kill: 3600
    task-success: 0

  punishment:
    disable-on-disallowed-team: false
    offline: 7200
    death: 3600
    boogey-death: 7200 # boogeyman
    task-failure: 7200 # secret/cat life


  # Options for player's final death (i.e. RED -> SPECTATOR)
  final-death:
    # Players will drop their heads on their final death (RED -> SPECTATOR)
    drop-head: true
    # DO not set keepInventory to true if you use this option. If this is set to true, the plugin will dictate when
    # players keep their items.
    keepinv-till-final: true
    lightning-strike: true
    respawn-after-final: true # when players die on final they wont see screen
    announce: true

  # Options for the end of the session ( /life endsession <delay> )
  end-of-session:
    # when <delay> is used, an announcement will be made with the time remaining, as well as 5 minutes before
    # (if the delay is long enough)
    warn-players: true
    # kick players at end of session
    # bypass permission: life.bypass.kick
    kick-at-end: true
